<?php
/**
 * @file
 * Module file for btrClient.
 */

require_once(dirname(__FILE__) . '/translations/utils.inc');
require_once(dirname(__FILE__) . '/btrClient.menu.inc');
require_once(dirname(__FILE__) . '/btrClient.blocks.inc');
require_once(dirname(__FILE__) . '/btrClient.services.inc');

/**
 * Implements hook_help().
 */
                               /*
function btrClient_help($path, $args) {
  switch($path)
    {
      case 'translations/get':
        $help = t('Get translation suggestions for a given string.');
        break;

      case 'translations/vote':
        $help = t('Vote the best translation for a string, or suggest a better translation.');
        break;
    }

  return $help;
}
                               */

/**
 * Implements hook_theme().
 */
function btrClient_theme($existing, $type, $theme, $path) {
  return array(
    'btrClient_filter_form_element' => array(
      'render element' => 'element',
    ),
    'btrClient_translate_translation' => array(
      'render element' => 'element',
    ),
    'btrClient_translate_actions' => array(
      'render element' => 'element',
    ),
    'btrClient_in_context' => array(
      'variables' => array('source' => NULL),
    ),
    'btrClient_translate_radio' => array(
      'render element' => 'element',
    ),
    'btrClient_translate_source' => array(
      'render element' => 'element',
    ),
    'btrClient_translate_translation_list' => array(
      'render element' => 'element',
    ),
    'btrClient_translate_table' => array(
      'render element' => 'element',
    ),
  );
}

/**
 * Implements hook_flush_caches().
 * Add cache table names to the list of cache tables
 * that will be cleared by the Clear button on the Performance page
 * or whenever drupal_flush_all_caches is invoked.
 * Returns an array of cache table names.
 */
function btrClient_flush_caches() {
  return array('cache_btrClient');
}

/**
 * Implements hook_init().
 */
function btrClient_init() {
  if (arg(0) == 'translations') {
    drupal_add_css(drupal_get_path('module', 'btrClient') . '/btrClient.css');
    // For the translation overview pages. This is used to present admin page like panels.
    drupal_add_css(drupal_get_path('module', 'system') . '/admin.css');
  }

  // Check if language is RTL
  $languages = btrClient_get_languages();
  $lng = arg(1);
  if (array_key_exists($lng, $languages)) {
    // Add RTL style if the current language's direction is RTL
    if ($languages[$lng]['direction'] == LANGUAGE_RTL) {
      drupal_add_css(drupal_get_path('module', 'btrClient') . '/btrClient-rtl.css');
    }
  }

  // Disable breadcrumb.
  drupal_set_breadcrumb(array());
}

/**
 * Implements hook_hybridauth_profile_alter().
 */
function btrClient_hybridauth_profile_alter($profile) {
  if (!isset($profile['remote_profile']))  return;

  $btr_user = $profile['remote_profile'];
  $btr_profile = array(
    'translation_lng' => $btr_user->translation_lng,
    'string_order' => $btr_user->string_order,
    'preferred_projects' => $btr_user->preferred_projects,
    'auxiliary_languages' => $btr_user->auxiliary_languages,
    'translations_per_day' => $btr_user->translations_per_day,
    'feedback_channels' => $btr_user->feedback_channels,
    'permissions' => $btr_user->permissions,
  );
  $_SESSION['btrClient']['btr_profile'] = $btr_profile;
}

/**
 * Implements hook_oauth2_login_enabled().
 */
function btrClient_oauth2_login_enabled($enabled) {
  db_update('menu_links')
    ->fields(array(
        'hidden' => ($enabled ? 1 : 0),
      ))
    ->condition('menu_name', 'user-menu')
    ->condition('link_path', 'user/login')
    ->condition('router_path', 'user/login')
    ->condition('plid', 0)
    ->condition('module', 'menu')
    ->execute();
}

/*
function btr_log($var, $comment ='') {
  $file = '/tmp/btr.log';
  $content = "\n==> $comment: " . print_r($var, true);
  file_put_contents($file, $content, FILE_APPEND);
}
*/