<?php
/**
 * @file
 * Module file for btrClientWS.
 */

/**
 * Implements hook_default_wsclient_service().
 *
 * Defines web service descriptions (one public and one private).
 * This hook is invoked when web service descriptions
 * are loaded like this:
 *     $btr = wsclient_service_load('dev.l10n.org.xx');
 *     $result = $btr->statistics('sq');
 */
function btrClientWS_default_wsclient_service() {
  module_load_include('inc', 'btrClientWS', 'public');
  module_load_include('inc', 'btrClientWS', 'authenticated');

  $services['public_btr'] = _btrClientWS_public('public_btr');
  $services['btr'] = _btrClientWS_authenticated('btr');
  return $services;
}
