<?php
/**
 * @file
 * Module file for btrVocabulary.
 */

module_load_include('inc', 'btrVocabulary', 'form_build');
module_load_include('inc', 'btrVocabulary', 'form_submit');

/**
 * Implements hook_menu().
 */
function btrVocabulary_menu() {
  $items['vocabulary'] = array(
    'title'           => 'Vocabulary',
    'description'     => 'Lookup vocabulary items.',
    'page callback'   => 'btrVocabulary_page',
    //'file'            => 'form.inc',
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Implements hook_menu_link_alter().
 */
function btrVocabulary_menu_link_alter(&$item) {
  // Open vocabulary on a new tab.
  if ($item['link_path'] == 'vocabulary') {
    $item['options']['attributes']['target'] = '_blank';
  }
}

/**
 * Implements hook_theme().
 */
function btrVocabulary_theme($existing, $type, $theme, $path) {
  return array(
    'btrVocabulary_table' => array(
      'render element' => 'element',
    ),
  );
}

/**
 * Menu callback: vocabulary.
 */
function btrVocabulary_page($vocabulary = NULL, $term = NULL) {
  if ($vocabulary == NULL) {
    $lng = bcl::get_translation_lng();
    $vocabulary = 'ICT_' . $lng;
    bcl::go_to("vocabulary/$vocabulary");
  }

  // Set the page title.
  drupal_set_title(t('Vocabulary: !vocabulary',
      array('!vocabulary' => $vocabulary),
      array('context' => 'set the page title')));

  // Add the stylesheet of btrVocabulary.
  $css_file = drupal_get_path('module', 'btrVocabulary');
  $css_file .= bcl::inside_iframe() ? '/style-iframe.css' : '/style.css';
  drupal_add_css($css_file);

  // Build and return the output.
  $output = drupal_get_form('btrVocabulary_form', $vocabulary, $term);
  return $output;
}
