<?php
/**
 * @file
 * Module file for btrVocabulary.
 */

/**
 * Implements hook_menu().
 */
function btrVocabulary_menu() {
  $items['vocabulary'] = array(
    'title'           => 'Vocabulary',
    'description'     => 'Lookup vocabulary items.',
    'page callback'   => 'btrVocabulary_page',
    'file'            => 'btrVocabulary.page.inc',
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Implements hook_menu_link_alter().
 */
function btrVocabulary_menu_link_alter(&$item) {
  // Open vocabulary on a new tab.
  if ($item['link_path'] == 'vocabulary') {
    $item['options']['attributes']['target'] = '_blank';
  }
}

/**
 * Implements hook_theme().
 */
function btrVocabulary_theme($existing, $type, $theme, $path) {
  return array(
    'btrVocabulary_table' => array(
      'render element' => 'element',
    ),
  );
}
